# Step 1

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import os

In [2]:
# Define path
path = r'C:\Users\Personal Computer\Documents\09.2022_Instacart_Basket_Analysis'

In [3]:
# Import order_products_merged.pkl 
ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'order_products_merged_days_hours_update.pkl'))

In [4]:
# first million records
df = ords_prods_merge[:1000000]

In [5]:
df.shape

(1000000, 22)

In [6]:
df.head(10)

,Unnamed: 0_x,Unnamed: 0.1,order_id,user_id,user_order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_order,product_id,...,Unnamed: 0_y,product_name,aisle_id,department_id,prices,_merge,price_range_loc,Busiest Day,Busiest Days,Busiest Hours
0,0,0,2539329,1,1,2,8,NaN,yes,196,...,195,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours
1,1,1,2398795,1,2,3,7,15.0,no,196,...,195,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Least Busy Days,Regularly Busy Hours
2,2,2,473747,1,3,3,12,21.0,no,196,...,195,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Least Busy Days,Regularly Busy Hours
3,3,3,2254736,1,4,4,7,29.0,no,196,...,195,Soda,77,7,9.0,both,Mid range product,Least Busy,Least Busy Days,Regularly Busy Hours
4,4,4,431534,1,5,4,15,28.0,no,196,...,195,Soda,77,7,9.0,both,Mid range product,Least Busy,Least Busy Days,Busiest Hours
5,5,5,3367565,1,6,2,7,19.0,no,196,...,195,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours
6,6,6,550135,1,7,1,9,20.0,no,196,...,195,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Regularly Busy Hours
7,7,7,3108588,1,8,1,14,14.0,no,196,...,195,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Busiest Hours
8,8,8,2295261,1,9,1,16,0.0,no,196,...,195,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Regularly Busy Hours
9,9,9,2550362,1,10,4,8,30.0,no,196,...,195,Soda,77,7,9.0,both,Mid range product,Least Busy,Least Busy Days,Regularly Busy Hours

In [7]:
#group by product name
df.groupby('product_name')

In [8]:
# Mean aggregation
df.groupby('department_id').agg({'user_order_number': ['mean']})

              user_order_number
                           mean
department_id
4                     18.825780
7                     17.472355
13                    17.993423
14                    19.246334
16                    19.463012
17                    11.294069
19                    19.305237
20                    17.599636

In [9]:
df.groupby('department_id')['user_order_number'].mean()

department_id
4     18.825780
7     17.472355
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
Name: user_order_number, dtype: float64

In [10]:
# Multiple aggregations
df.groupby('department_id').agg({'user_order_number': ['mean', 'min', 'max']})

              user_order_number
                           mean min max
department_id
4                     18.825780   1  99
7                     17.472355   1  99
13                    17.993423   1  99
14                    19.246334   1  99
16                    19.463012   1  99
17                    11.294069   1  98
19                    19.305237   1  99
20                    17.599636   1  99

In [11]:
# Aggregation; creating a loyalty flag
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['user_order_number'].transform(np.max)

In [12]:
ords_prods_merge.head(15)

,Unnamed: 0_x,Unnamed: 0.1,order_id,user_id,user_order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_order,product_id,...,product_name,aisle_id,department_id,prices,_merge,price_range_loc,Busiest Day,Busiest Days,Busiest Hours,max_order
0,0,0,2539329,1,1,2,8,NaN,yes,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,10
1,1,1,2398795,1,2,3,7,15.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Least Busy Days,Regularly Busy Hours,10
2,2,2,473747,1,3,3,12,21.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Least Busy Days,Regularly Busy Hours,10
3,3,3,2254736,1,4,4,7,29.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Least Busy,Least Busy Days,Regularly Busy Hours,10
4,4,4,431534,1,5,4,15,28.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Least Busy,Least Busy Days,Busiest Hours,10
5,5,5,3367565,1,6,2,7,19.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,10
6,6,6,550135,1,7,1,9,20.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Regularly Busy Hours,10
7,7,7,3108588,1,8,1,14,14.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Busiest Hours,10
8,8,8,2295261,1,9,1,16,0.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Regularly Busy Hours,10
9,9,9,2550362,1,10,4,8,30.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Least Busy,Least Busy Days,Regularly Busy Hours,10
10,144,144,2968173,15,15,1,9,7.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Regularly Busy Hours,22
11,146,146,1870022,15,17,2,16,8.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,22
12,147,147,1911383,15,18,2,11,7.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Busiest Hours,22
13,150,150,2715276,15,21,1,9,7.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Regularly Busy Hours,22
14,151,151,487368,15,22,1,10,14.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Busiest Hours,22

In [13]:
ords_prods_merge.head(100)

,Unnamed: 0_x,Unnamed: 0.1,order_id,user_id,user_order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_order,product_id,...,product_name,aisle_id,department_id,prices,_merge,price_range_loc,Busiest Day,Busiest Days,Busiest Hours,max_order
0,0,0,2539329,1,1,2,8,NaN,yes,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,10
1,1,1,2398795,1,2,3,7,15.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Least Busy Days,Regularly Busy Hours,10
2,2,2,473747,1,3,3,12,21.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Least Busy Days,Regularly Busy Hours,10
3,3,3,2254736,1,4,4,7,29.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Least Busy,Least Busy Days,Regularly Busy Hours,10
4,4,4,431534,1,5,4,15,28.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Least Busy,Least Busy Days,Busiest Hours,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,5895,5895,3226575,360,1,5,12,NaN,yes,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,3
96,6137,6137,1469869,377,3,5,17,3.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,3
97,6259,6259,1927023,387,2,4,10,22.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Least Busy,Least Busy Days,Busiest Hours,8
98,6740,6740,858092,420,4,1,19,30.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Regularly Busy Hours,22
99,6741,6741,119314,420,5,3,19,16.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Least Busy Days,Regularly Busy Hours,22

In [14]:
# All 100 rows
pd.options.display.max_rows = None
ords_prods_merge.head(100)

,Unnamed: 0_x,Unnamed: 0.1,order_id,user_id,user_order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_order,product_id,...,product_name,aisle_id,department_id,prices,_merge,price_range_loc,Busiest Day,Busiest Days,Busiest Hours,max_order
0,0,0,2539329,1,1,2,8,NaN,yes,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,10
1,1,1,2398795,1,2,3,7,15.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Least Busy Days,Regularly Busy Hours,10
2,2,2,473747,1,3,3,12,21.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Least Busy Days,Regularly Busy Hours,10
3,3,3,2254736,1,4,4,7,29.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Least Busy,Least Busy Days,Regularly Busy Hours,10
4,4,4,431534,1,5,4,15,28.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Least Busy,Least Busy Days,Busiest Hours,10
5,5,5,3367565,1,6,2,7,19.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,10
6,6,6,550135,1,7,1,9,20.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Regularly Busy Hours,10
7,7,7,3108588,1,8,1,14,14.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Busiest Hours,10
8,8,8,2295261,1,9,1,16,0.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Regularly Busy Hours,10
9,9,9,2550362,1,10,4,8,30.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Least Busy,Least Busy Days,Regularly Busy Hours,10
10,144,144,2968173,15,15,1,9,7.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Regularly Busy Hours,22
11,146,146,1870022,15,17,2,16,8.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,22
12,147,147,1911383,15,18,2,11,7.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Busiest Hours,22
13,150,150,2715276,15,21,1,9,7.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Regularly Busy Hours,22
14,151,151,487368,15,22,1,10,14.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Busiest Hours,22
15,209,209,2293453,19,2,5,14,6.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Busiest Hours,9
16,212,212,1973799,19,5,6,12,8.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,9
17,214,214,532817,19,7,4,17,6.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Least Busy,Least Busy Days,Regularly Busy Hours,9
18,232,232,1573906,21,10,3,10,6.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Least Busy Days,Busiest Hours,33
19,458,458,1593000,31,10,3,8,7.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Least Busy Days,Regularly Busy Hours,20
20,465,465,2231262,31,17,3,11,8.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Least Busy Days,Busiest Hours,20
21,617,617,2580647,43,6,4,16,4.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Least Busy,Least Busy Days,Regularly Busy Hours,11
22,620,620,2187180,43,9,4,12,3.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Least Busy,Least Busy Days,Regularly Busy Hours,11
23,751,751,2497897,52,1,1,9,NaN,yes,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Regularly Busy Hours,27
24,752,752,1318871,52,2,1,10,7.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Busiest Hours,27
25,753,753,1261384,52,3,1,10,7.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Busiest Hours,27
26,755,755,580568,52,5,2,10,8.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Busiest Hours,27
27,757,757,2428073,52,7,2,7,8.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,27
28,759,759,342306,52,9,1,11,7.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Busiest Hours,27
29,760,760,1520353,52,10,2,10,8.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Busiest Hours,27
30,761,761,2542086,52,11,2,9,7.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,27
31,762,762,944694,52,12,1,16,6.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Regularly Busy Hours,27
32,765,765,1268191,52,15,2,11,8.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Busiest Hours,27
33,767,767,1122089,52,17,2,10,6.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Busiest Hours,27
34,768,768,1498922,52,18,2,10,14.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Busiest Hours,27
35,769,769,180919,52,19,3,8,8.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Least Busy Days,Regularly Busy Hours,27
36,771,771,2695875,52,21,5,10,30.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Busiest Hours,27
37,1022,1022,3205960,67,1,3,11,NaN,yes,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Least Busy Days,Busiest Hours,24
38,1023,1023,970922,67,2,1,15,5.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Busiest Hours,24
39,1024,1024,596585,67,3,1,13,7.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Regularly Busy Hours,24
40,1025,1025,2037087,67,4,2,9,8.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,24
41,1026,1026,2474111,67,5,3,14,8.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Least Busy Days,Busiest Hours,24
42,1027,1027,1568481,67,6,3,12,7.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Least Busy Days,Regularly Busy Hours,24
43,1029,1029,2048527,67,8,2,11,7.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Busiest Hours,24
44,1030,1030,2389031,67,9,2,14,7.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Busiest Hours,24
45,1031,1031,2378562,67,10,1,10,6.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Busiest Hours,24
46,1032,1032,1515698,67,11,1,11,7.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Busiest Hours,24
47,1033,1033,1928050,67,12,2,12,8.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,24
48,1034,1034,1949274,67,13,1,10,6.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Busiest Hours,24
49,1035,1035,551869,67,14,1,9,7.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Regularly Busy Hours,24
50,1037,1037,768572,67,16,4,10,9.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Least Busy,Least Busy Days,Busiest Hours,24
51,1039,1039,150528,67,18,5,16,4.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,24
52,1040,1040,29758,67,19,0,14,9.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Busiest Day,Busiest Days,Busiest Hours,24
53,1042,1042,1558976,67,21,1,9,5.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Regularly Busy Hours,24
54,1043,1043,863974,67,22,1,11,14.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Busiest Hours,24
55,1044,1044,2308399,67,23,1,14,14.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Busiest Hours,24
56,1202,1202,2759128,81,3,1,9,14.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Regularly Busy Hours,7
57,1204,1204,1812985,81,5,2,20,30.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,7
58,1208,1208,1889835,82,1,3,15,NaN,yes,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Least Busy Days,Busiest Hours,19
59,1210,1210,499460,82,3,5,10,5.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Busiest Hours,19
60,1211,1211,2728456,82,4,0,11,16.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Busiest Day,Busiest Days,Busiest Hours,19
61,1213,1213,2653743,82,6,4,9,13.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Least Busy,Least Busy Days,Regularly Busy Hours,19
62,1216,1216,1358880,82,9,1,10,30.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Busiest Hours,19
63,1217,1217,343588,82,10,2,11,1.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Busiest Hours,19
64,1222,1222,3034663,82,15,2,11,12.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Busiest Hours,19
65,1225,1225,147262,82,18,1,13,7.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Regularly Busy Hours,19
66,1226,1226,3144004,82,19,2,15,8.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Busiest Hours,19
67,1480,1480,2126069,98,3,0,9,25.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Busiest Day,Busiest Days,Regularly Busy Hours,14
68,1484,1484,2210120,98,7,5,14,5.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Busiest Hours,14
69,1486,1486,681011,98,9,3,9,30.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Least Busy Days,Regularly Busy Hours,14
70,1488,1488,2846344,98,11,4,13,15.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Least Busy,Least Busy Days,Regularly Busy Hours,14
71,1489,1489,747431,98,12,6,13,30.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,14
72,1490,1490,2383054,98,13,4,11,30.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Least Busy,Least Busy Days,Busiest Hours,14
73,1491,1491,1993729,98,14,5,8,8.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,14
74,1608,1608,1403849,109,3,3,17,9.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Least Busy Days,Regularly Busy Hours,6
75,1744,1744,520620,120,1,3,11,NaN,yes,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Least Busy Days,Busiest Hours,3
76,1746,1746,3273029,120,3,2,8,19.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,3
77,2781,2781,1861943,185,2,1,12,25.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Regularly Busy Hours,6
78,2891,2891,2040988,195,1,1,14,NaN,yes,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Busiest Hours,58
79,2898,2898,1680569,195,8,1,9,4.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Regularly Busy Hours,58
80,2909,2909,276171,195,19,5,11,3.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Busiest Hours,58
81,2912,2912,2744976,195,22,5,10,7.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Busiest Hours,58
82,2915,2915,2781919,195,25,1,14,4.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Busiest Hours,58
83,2921,2921,1738718,195,31,2,8,4.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,58
84,2924,2924,3058369,195,34,3,10,6.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Least Busy Days,Busiest Hours,58
85,2927,2927,1485596,195,37,2,15,0.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Busiest Hours,58
86,2930,2930,417035,195,40,3,16,2.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Least Busy Days,Regularly Busy Hours,58
87,2937,2937,1615297,195,47,5,10,2.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Busiest Hours,58
88,2942,2942,1765587,195,52,3,12,2.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Least Busy Days,Regularly Busy Hours,58
89,2947,2947,745908,195,57,4,11,3.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Least Busy,Least Busy Days,Busiest Hours,58
90,3451,3451,2505656,222,17,2,12,1.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,70
91,3472,3472,3268370,222,38,5,15,1.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Busiest Hours,70
92,4667,4667,2016711,290,9,5,19,6.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,51
93,4686,4686,2706088,290,28,6,10,7.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Busiest Hours,51
94,5551,5551,1952286,331,6,5,16,30.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,8
95,5895,5895,3226575,360,1,5,12,NaN,yes,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,3
96,6137,6137,1469869,377,3,5,17,3.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Regularly Busy Days,Regularly Busy Hours,3
97,6259,6259,1927023,387,2,4,10,22.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Least Busy,Least Busy Days,Busiest Hours,8
98,6740,6740,858092,420,4,1,19,30.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Busiest Days,Regularly Busy Hours,22
99,6741,6741,119314,420,5,3,19,16.0,no,196,...,Soda,77,7,9.0,both,Mid range product,Regularly Busy,Least Busy Days,Regularly Busy Hours,22

In [15]:
# Deriving Columns; Loyalty Flags
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [16]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [17]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [18]:
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

In [19]:
ords_prods_merge[['user_id', 'loyalty_flag', 'user_order_number']].head(60)

    user_id      loyalty_flag  user_order_number
0         1      New customer                  1
1         1      New customer                  2
2         1      New customer                  3
3         1      New customer                  4
4         1      New customer                  5
5         1      New customer                  6
6         1      New customer                  7
7         1      New customer                  8
8         1      New customer                  9
9         1      New customer                 10
10       15  Regular customer                 15
11       15  Regular customer                 17
12       15  Regular customer                 18
13       15  Regular customer                 21
14       15  Regular customer                 22
15       19      New customer                  2
16       19      New customer                  5
17       19      New customer                  7
18       21  Regular customer                 10
19       31  Regular customer                 10
20       31  Regular customer                 17
21       43  Regular customer                  6
22       43  Regular customer                  9
23       52  Regular customer                  1
24       52  Regular customer                  2
25       52  Regular customer                  3
26       52  Regular customer                  5
27       52  Regular customer                  7
28       52  Regular customer                  9
29       52  Regular customer                 10
30       52  Regular customer                 11
31       52  Regular customer                 12
32       52  Regular customer                 15
33       52  Regular customer                 17
34       52  Regular customer                 18
35       52  Regular customer                 19
36       52  Regular customer                 21
37       67  Regular customer                  1
38       67  Regular customer                  2
39       67  Regular customer                  3
40       67  Regular customer                  4
41       67  Regular customer                  5
42       67  Regular customer                  6
43       67  Regular customer                  8
44       67  Regular customer                  9
45       67  Regular customer                 10
46       67  Regular customer                 11
47       67  Regular customer                 12
48       67  Regular customer                 13
49       67  Regular customer                 14
50       67  Regular customer                 16
51       67  Regular customer                 18
52       67  Regular customer                 19
53       67  Regular customer                 21
54       67  Regular customer                 22
55       67  Regular customer                 23
56       81      New customer                  3
57       81      New customer                  5
58       82  Regular customer                  1
59       82  Regular customer                  3

# Step 2

In [25]:
# Mean aggregation for entire dataframe
ords_prods_merge.groupby('department_id').agg({'user_order_number': ['mean','min','max']})

              user_order_number
                           mean min max
department_id
1                     15.457838   1  99
2                     17.277920   1  99
3                     17.170395   1  99
4                     17.811403   1  99
5                     15.215751   1  99
6                     16.439806   1  99
7                     17.225802   1  99
8                     15.340650   1  99
9                     15.895474   1  99
10                    20.197148   1  99
11                    16.170638   1  99
12                    15.887671   1  99
13                    16.583536   1  99
14                    16.773669   1  99
15                    16.165037   1  99
16                    17.665606   1  99
17                    15.694469   1  99
18                    19.310397   1  99
19                    17.177343   1  99
20                    16.473447   1  99
21                    22.902379   1  99

In [24]:
ords_prods_merge.shape

(32404859, 24)

In [21]:
df1i = pd.DataFrame({
    'dep_id':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21],
    'mean_num':[15.457838, 17.277920, 17.170395, 17.811403, 15.215751, 16.439806, 17.225802, 15.340650, 15.895474, 20.197148, 16.170638, 15.887671, 16.583536, 16.773669, 16.165037, 17.665606, 15.694469, 19.310397, 17.177343, 16.473447, 22.902379]
})
df2i = pd.DataFrame({
    'dep_id':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21],
    'mean_num':[0, 0, 0, 18.825780, 0, 0, 17.472355, 0, 0, 0, 0, 0, 17.993423, 19.246334, 0, 19.463012, 11.294069, 0, 19.305237, 17.599636, 0]
})

In [22]:
df1i.compare(df2i)

     mean_num
         self      other
0   15.457838   0.000000
1   17.277920   0.000000
2   17.170395   0.000000
3   17.811403  18.825780
4   15.215751   0.000000
5   16.439806   0.000000
6   17.225802  17.472355
7   15.340650   0.000000
8   15.895474   0.000000
9   20.197148   0.000000
10  16.170638   0.000000
11  15.887671   0.000000
12  16.583536  17.993423
13  16.773669  19.246334
14  16.165037   0.000000
15  17.665606  19.463012
16  15.694469  11.294069
17  19.310397   0.000000
18  17.177343  19.305237
19  16.473447  17.599636
20  22.902379   0.000000

### The first million rows brings back only 8 different departments compared to the full set; do so there is a lot of data not accounted for

# Step 4

## Instruction: follow the instructions in the Exercise for creating a loyalty flag for existing customers using the transform() and loc()functions

## i believe this was already done in Step 1

In [23]:
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

# Step 5

In [28]:
ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean','max','min']})

                     prices
                       mean      max  min
loyalty_flag
Loyal customer    10.386336  99999.0  1.0
New customer      13.294670  99999.0  1.0
Regular customer  12.495717  99999.0  1.0

## It appears that loyal customers on average tend to pay lower prices than regular and new customers; the max and min prices don't provide us with any discernable information.

# Step 6

In [29]:
# Aggregation; creating a spending flag to identify High spenders (over 10)
ords_prods_merge['mean_order_price'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [35]:
# Deriving Columns; Spending Flags
ords_prods_merge.loc[ords_prods_merge['mean_order_price'] >= 10, 'spending_flag'] = 'Big spender'
ords_prods_merge.loc[ords_prods_merge['mean_order_price'] < 10, 'spending_flag'] = 'Low spender'

In [36]:
ords_prods_merge['spending_flag'].value_counts(dropna = False)

Low spender    31770614
Big spender      634245
Name: spending_flag, dtype: int64

In [39]:
ords_prods_merge[['user_id', 'loyalty_flag', 'spending_flag', 'mean_order_price']].head(100)

    user_id      loyalty_flag spending_flag  mean_order_price
0         1      New customer   Low spender          6.367797
1         1      New customer   Low spender          6.367797
2         1      New customer   Low spender          6.367797
3         1      New customer   Low spender          6.367797
4         1      New customer   Low spender          6.367797
5         1      New customer   Low spender          6.367797
6         1      New customer   Low spender          6.367797
7         1      New customer   Low spender          6.367797
8         1      New customer   Low spender          6.367797
9         1      New customer   Low spender          6.367797
10       15  Regular customer   Low spender          3.980556
11       15  Regular customer   Low spender          3.980556
12       15  Regular customer   Low spender          3.980556
13       15  Regular customer   Low spender          3.980556
14       15  Regular customer   Low spender          3.980556
15       19      New customer   Low spender          8.372059
16       19      New customer   Low spender          8.372059
17       19      New customer   Low spender          8.372059
18       21  Regular customer   Low spender          7.012683
19       31  Regular customer   Low spender          8.137793
20       31  Regular customer   Low spender          8.137793
21       43  Regular customer   Low spender          7.444898
22       43  Regular customer   Low spender          7.444898
23       52  Regular customer   Low spender          6.356287
24       52  Regular customer   Low spender          6.356287
25       52  Regular customer   Low spender          6.356287
26       52  Regular customer   Low spender          6.356287
27       52  Regular customer   Low spender          6.356287
28       52  Regular customer   Low spender          6.356287
29       52  Regular customer   Low spender          6.356287
30       52  Regular customer   Low spender          6.356287
31       52  Regular customer   Low spender          6.356287
32       52  Regular customer   Low spender          6.356287
33       52  Regular customer   Low spender          6.356287
34       52  Regular customer   Low spender          6.356287
35       52  Regular customer   Low spender          6.356287
36       52  Regular customer   Low spender          6.356287
37       67  Regular customer   Low spender          7.656790
38       67  Regular customer   Low spender          7.656790
39       67  Regular customer   Low spender          7.656790
40       67  Regular customer   Low spender          7.656790
41       67  Regular customer   Low spender          7.656790
42       67  Regular customer   Low spender          7.656790
43       67  Regular customer   Low spender          7.656790
44       67  Regular customer   Low spender          7.656790
45       67  Regular customer   Low spender          7.656790
46       67  Regular customer   Low spender          7.656790
47       67  Regular customer   Low spender          7.656790
48       67  Regular customer   Low spender          7.656790
49       67  Regular customer   Low spender          7.656790
50       67  Regular customer   Low spender          7.656790
51       67  Regular customer   Low spender          7.656790
52       67  Regular customer   Low spender          7.656790
53       67  Regular customer   Low spender          7.656790
54       67  Regular customer   Low spender          7.656790
55       67  Regular customer   Low spender          7.656790
56       81      New customer   Low spender          8.165385
57       81      New customer   Low spender          8.165385
58       82  Regular customer   Low spender          6.441221
59       82  Regular customer   Low spender          6.441221
60       82  Regular customer   Low spender          6.441221
61       82  Regular customer   Low spender          6.441221
62       82  Regular customer   Low spender          6.441221
63       82  Regular customer   Low spender          6.441221
64       82  Regular customer   Low spender          6.441221
65       82  Regular customer   Low spender          6.441221
66       82  Regular customer   Low spender          6.441221
67       98  Regular customer   Low spender          8.028000
68       98  Regular customer   Low spender          8.028000
69       98  Regular customer   Low spender          8.028000
70       98  Regular customer   Low spender          8.028000
71       98  Regular customer   Low spender          8.028000
72       98  Regular customer   Low spender          8.028000
73       98  Regular customer   Low spender          8.028000
74      109      New customer   Low spender          5.850725
75      120      New customer   Low spender          9.385714
76      120      New customer   Low spender          9.385714
77      185      New customer   Low spender          7.715000
78      195    Loyal customer   Low spender          7.149730
79      195    Loyal customer   Low spender          7.149730
80      195    Loyal customer   Low spender          7.149730
81      195    Loyal customer   Low spender          7.149730
82      195    Loyal customer   Low spender          7.149730
83      195    Loyal customer   Low spender          7.149730
84      195    Loyal customer   Low spender          7.149730
85      195    Loyal customer   Low spender          7.149730
86      195    Loyal customer   Low spender          7.149730
87      195    Loyal customer   Low spender          7.149730
88      195    Loyal customer   Low spender          7.149730
89      195    Loyal customer   Low spender          7.149730
90      222    Loyal customer   Low spender          6.862397
91      222    Loyal customer   Low spender          6.862397
92      290    Loyal customer   Low spender          7.285597
93      290    Loyal customer   Low spender          7.285597
94      331      New customer   Low spender          7.705128
95      360      New customer   Big spender         10.006250
96      377      New customer   Low spender          8.496552
97      387      New customer   Low spender          7.396610
98      420  Regular customer   Low spender          7.387805
99      420  Regular customer   Low spender          7.387805

# Step 7

In [40]:
# Aggregation; creating a spending flag to identify Non-Frequent, Frequent and Regular Customers
ords_prods_merge['median_prior_order'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [41]:
# Deriving Columns; Frequency Flags
ords_prods_merge.loc[ords_prods_merge['median_prior_order'] > 20, 'frequency_flag'] = 'Non-Frequent Customer'

In [45]:
ords_prods_merge.loc[(ords_prods_merge['median_prior_order'] <= 20) & (ords_prods_merge['median_prior_order'] > 10), 'frequency_flag'] = 'Regular-Frequency Customer'

In [46]:
ords_prods_merge.loc[ords_prods_merge['median_prior_order'] <= 10, 'frequency_flag'] = 'Frequent Customer'

In [47]:
ords_prods_merge[['user_id', 'loyalty_flag', 'spending_flag', 'mean_order_price', 'frequency_flag', 'median_prior_order']].head(100)

,user_id,loyalty_flag,spending_flag,mean_order_price,frequency_flag,median_prior_order
0,1,New customer,Low spender,6.367797,Non-Frequent Customer,20.5
1,1,New customer,Low spender,6.367797,Non-Frequent Customer,20.5
2,1,New customer,Low spender,6.367797,Non-Frequent Customer,20.5
3,1,New customer,Low spender,6.367797,Non-Frequent Customer,20.5
4,1,New customer,Low spender,6.367797,Non-Frequent Customer,20.5
5,1,New customer,Low spender,6.367797,Non-Frequent Customer,20.5
6,1,New customer,Low spender,6.367797,Non-Frequent Customer,20.5
7,1,New customer,Low spender,6.367797,Non-Frequent Customer,20.5
8,1,New customer,Low spender,6.367797,Non-Frequent Customer,20.5
9,1,New customer,Low spender,6.367797,Non-Frequent Customer,20.5
10,15,Regular customer,Low spender,3.980556,Frequent Customer,10.0
11,15,Regular customer,Low spender,3.980556,Frequent Customer,10.0
12,15,Regular customer,Low spender,3.980556,Frequent Customer,10.0
13,15,Regular customer,Low spender,3.980556,Frequent Customer,10.0
14,15,Regular customer,Low spender,3.980556,Frequent Customer,10.0
15,19,New customer,Low spender,8.372059,Frequent Customer,6.0
16,19,New customer,Low spender,8.372059,Frequent Customer,6.0
17,19,New customer,Low spender,8.372059,Frequent Customer,6.0
18,21,Regular customer,Low spender,7.012683,Frequent Customer,7.5
19,31,Regular customer,Low spender,8.137793,Frequent Customer,6.0
20,31,Regular customer,Low spender,8.137793,Frequent Customer,6.0
21,43,Regular customer,Low spender,7.444898,Frequent Customer,10.0
22,43,Regular customer,Low spender,7.444898,Frequent Customer,10.0
23,52,Regular customer,Low spender,6.356287,Frequent Customer,8.0
24,52,Regular customer,Low spender,6.356287,Frequent Customer,8.0
25,52,Regular customer,Low spender,6.356287,Frequent Customer,8.0
26,52,Regular customer,Low spender,6.356287,Frequent Customer,8.0
27,52,Regular customer,Low spender,6.356287,Frequent Customer,8.0
28,52,Regular customer,Low spender,6.356287,Frequent Customer,8.0
29,52,Regular customer,Low spender,6.356287,Frequent Customer,8.0
30,52,Regular customer,Low spender,6.356287,Frequent Customer,8.0
31,52,Regular customer,Low spender,6.356287,Frequent Customer,8.0
32,52,Regular customer,Low spender,6.356287,Frequent Customer,8.0
33,52,Regular customer,Low spender,6.356287,Frequent Customer,8.0
34,52,Regular customer,Low spender,6.356287,Frequent Customer,8.0
35,52,Regular customer,Low spender,6.356287,Frequent Customer,8.0
36,52,Regular customer,Low spender,6.356287,Frequent Customer,8.0
37,67,Regular customer,Low spender,7.656790,Frequent Customer,7.0
38,67,Regular customer,Low spender,7.656790,Frequent Customer,7.0
39,67,Regular customer,Low spender,7.656790,Frequent Customer,7.0
40,67,Regular customer,Low spender,7.656790,Frequent Customer,7.0
41,67,Regular customer,Low spender,7.656790,Frequent Customer,7.0
42,67,Regular customer,Low spender,7.656790,Frequent Customer,7.0
43,67,Regular customer,Low spender,7.656790,Frequent Customer,7.0
44,67,Regular customer,Low spender,7.656790,Frequent Customer,7.0
45,67,Regular customer,Low spender,7.656790,Frequent Customer,7.0
46,67,Regular customer,Low spender,7.656790,Frequent Customer,7.0
47,67,Regular customer,Low spender,7.656790,Frequent Customer,7.0
48,67,Regular customer,Low spender,7.656790,Frequent Customer,7.0
49,67,Regular customer,Low spender,7.656790,Frequent Customer,7.0
50,67,Regular customer,Low spender,7.656790,Frequent Customer,7.0
51,67,Regular customer,Low spender,7.656790,Frequent Customer,7.0
52,67,Regular customer,Low spender,7.656790,Frequent Customer,7.0
53,67,Regular customer,Low spender,7.656790,Frequent Customer,7.0
54,67,Regular customer,Low spender,7.656790,Frequent Customer,7.0
55,67,Regular customer,Low spender,7.656790,Frequent Customer,7.0
56,81,New customer,Low spender,8.165385,Non-Frequent Customer,30.0
57,81,New customer,Low spender,8.165385,Non-Frequent Customer,30.0
58,82,Regular customer,Low spender,6.441221,Regular-Frequency Customer,11.5
59,82,Regular customer,Low spender,6.441221,Regular-Frequency Customer,11.5
60,82,Regular customer,Low spender,6.441221,Regular-Frequency Customer,11.5
61,82,Regular customer,Low spender,6.441221,Regular-Frequency Customer,11.5
62,82,Regular customer,Low spender,6.441221,Regular-Frequency Customer,11.5
63,82,Regular customer,Low spender,6.441221,Regular-Frequency Customer,11.5
64,82,Regular customer,Low spender,6.441221,Regular-Frequency Customer,11.5
65,82,Regular customer,Low spender,6.441221,Regular-Frequency Customer,11.5
66,82,Regular customer,Low spender,6.441221,Regular-Frequency Customer,11.5
67,98,Regular customer,Low spender,8.028000,Non-Frequent Customer,25.0
68,98,Regular customer,Low spender,8.028000,Non-Frequent Customer,25.0
69,98,Regular customer,Low spender,8.028000,Non-Frequent Customer,25.0
70,98,Regular customer,Low spender,8.028000,Non-Frequent Customer,25.0
71,98,Regular customer,Low spender,8.028000,Non-Frequent Customer,25.0
72,98,Regular customer,Low spender,8.028000,Non-Frequent Customer,25.0
73,98,Regular customer,Low spender,8.028000,Non-Frequent Customer,25.0
74,109,New customer,Low spender,5.850725,Non-Frequent Customer,26.0
75,120,New customer,Low spender,9.385714,Regular-Frequency Customer,19.0
76,120,New customer,Low spender,9.385714,Regular-Frequency Customer,19.0
77,185,New customer,Low spender,7.715000,Non-Frequent Customer,25.0
78,195,Loyal customer,Low spender,7.149730,Frequent Customer,4.0
79,195,Loyal customer,Low spender,7.149730,Frequent Customer,4.0
80,195,Loyal customer,Low spender,7.149730,Frequent Customer,4.0
81,195,Loyal customer,Low spender,7.149730,Frequent Customer,4.0
82,195,Loyal customer,Low spender,7.149730,Frequent Customer,4.0
83,195,Loyal customer,Low spender,7.149730,Frequent Customer,4.0
84,195,Loyal customer,Low spender,7.149730,Frequent Customer,4.0
85,195,Loyal customer,Low spender,7.149730,Frequent Customer,4.0
86,195,Loyal customer,Low spender,7.149730,Frequent Customer,4.0
87,195,Loyal customer,Low spender,7.149730,Frequent Customer,4.0
88,195,Loyal customer,Low spender,7.149730,Frequent Customer,4.0
89,195,Loyal customer,Low spender,7.149730,Frequent Customer,4.0
90,222,Loyal customer,Low spender,6.862397,Frequent Customer,5.0
91,222,Loyal customer,Low spender,6.862397,Frequent Customer,5.0
92,290,Loyal customer,Low spender,7.285597,Frequent Customer,7.0
93,290,Loyal customer,Low spender,7.285597,Frequent Customer,7.0
94,331,New customer,Low spender,7.705128,Non-Frequent Customer,30.0
95,360,New customer,Big spender,10.006250,Frequent Customer,4.0
96,377,New customer,Low spender,8.496552,Regular-Frequency Customer,16.5
97,387,New customer,Low spender,7.396610,Frequent Customer,8.0
98,420,Regular customer,Low spender,7.387805,Frequent Customer,7.0
99,420,Regular customer,Low spender,7.387805,Frequent Customer,7.0

# Step 8 & 9

In [48]:
ords_prods_merge.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'order_products_merged_day_hrs_grouped_updated.pkl'))

In [ ]:
zipped=zip(departments['Unnamed: 0.'], departments['department'])
data_dict=dict(zipped)
data_dict